//! Provides interfaces for rebuilding snapshot storages

use {
    super::SnapshotError,
    crate::serde_snapshot::{SerdeObsoleteAccounts, remap_append_vec_file},
    agave_fs::FileInfo,
    log::*,
    solana_accounts_db::{
        ObsoleteAccounts,
        account_storage::AccountStorageMap,
        account_storage_entry::AccountStorageEntry,
        accounts_db::{AccountsFileId, AtomicAccountsFileId},
        accounts_file::AccountsFile,
    },
    solana_clock::Slot,
    std::{
        collections::HashMap,
        path::PathBuf,
        str::FromStr as _,
        sync::{Arc, atomic::Ordering},
        time::{Duration, Instant},
    },
};

const PROGRESS_LOG_INTERVAL: Duration = Duration::from_secs(2);

/// Holds state for rebuilding snapshot storages
#[derive(Debug)]
pub(crate) struct SnapshotStorageRebuilder {
    /// Container for storing rebuilt snapshot storages
    storage: AccountStorageMap,
    /// Tracks next append_vec_id
    next_append_vec_id: Arc<AtomicAccountsFileId>,
    /// Tracks the number of collisions in AccountsFileId
    num_collisions: usize,
    /// Number of storage slots that have been rebuilt so far
    processed_slot_count: usize,
}

impl SnapshotStorageRebuilder {
    fn new(next_append_vec_id: Arc<AtomicAccountsFileId>) -> Self {
        Self {
            storage: AccountStorageMap::default(),
            next_append_vec_id,
            num_collisions: 0,
            processed_slot_count: 0,
        }
    }

    /// Rebuilds the account storages from a snapshot archive.
    pub(crate) fn rebuild_storages_from_snapshot_archive(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                // A snapshot archive only contains storages in AppendVec format.
                // And never contains separate ObsoleteAccounts information.
                // The IDs may overlap though, if the full and incremental snapshots
                // were generated by different nodes.
                let (remapped_id, remapped_file_info) = remap_append_vec_file(
                    slot,
                    id,
                    file_info,
                    &rebuilder.next_append_vec_id,
                    &mut rebuilder.num_collisions,
                )?;
                let accounts_file = AccountsFile::new_for_startup(remapped_file_info)?;
                let storage_entry = AccountStorageEntry::new_existing(
                    slot,
                    remapped_id,
                    accounts_file,
                    ObsoleteAccounts::default(),
                );

                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        Ok(rebuilder.storage)
    }

    /// Rebuilds the account storages from local state.
    pub(crate) fn rebuild_storages_from_local_state(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
        mut obsolete_accounts: HashMap<Slot, SerdeObsoleteAccounts>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                // When restoring from local state, obsolete accounts will be 'Some' if the storage
                // contained accounts marked obsolete at the time the snapshot was taken.
                // IDs will never overlap.
                let id = AccountsFileId::try_from(id).unwrap();
                let obsolete_accounts = obsolete_accounts
                    .remove(&slot)
                    .map(|accounts| accounts.into_tuple());
                let obsolete_accounts =
                    if let Some((obsolete_accounts, obsolete_id, _bytes)) = obsolete_accounts {
                        if obsolete_id != id {
                            return Err(SnapshotError::MismatchedAccountsFileId(id, obsolete_id));
                        }
                        obsolete_accounts
                    } else {
                        ObsoleteAccounts::default()
                    };
                let accounts_file = AccountsFile::new_for_startup(file_info)?;
                let storage_entry =
                    AccountStorageEntry::new_existing(slot, id, accounts_file, obsolete_accounts);

                // Keep track of the highest append_vec_id in the system, so the future append_vecs
                // can be assigned to unique IDs.  This is only needed when loading from local
                // state.  When loading from a snapshot archive, the max of the appendvec IDs is
                // updated in remap_append_vec_file(), which is not in the from_local_state route.
                rebuilder
                    .next_append_vec_id
                    .fetch_max(id + 1, Ordering::Relaxed);
                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        Ok(rebuilder.storage)
    }

    /// Logs the progress of rebuilding storages, if it has been
    /// `PROGRESS_LOG_INTERVAL` since the previous log.
    fn maybe_log_progress(&self, previous_log_time: &mut Instant) {
        let now = Instant::now();
        if now.duration_since(*previous_log_time) >= PROGRESS_LOG_INTERVAL {
            info!(
                "rebuilt storages for {} slots with {} collisions",
                self.processed_slot_count, self.num_collisions,
            );
            *previous_log_time = now;
        }
    }

    fn insert_storage(
        &mut self,
        slot: Slot,
        storage_entry: Arc<solana_accounts_db::account_storage_entry::AccountStorageEntry>,
    ) -> Result<(), SnapshotError> {
        let storage_id = storage_entry.id();
        if let Some(other) = self.storage.insert(slot, storage_entry) {
            Err(SnapshotError::RebuildStorages(format!(
                "there must be exactly one storage per slot, but slot {slot} has duplicate \
                 storages: {} vs {storage_id}",
                other.id()
            )))
        } else {
            Ok(())
        }
    }
}

/// Get the slot and append vec id from the filename
pub(crate) fn get_slot_and_append_vec_id(filename: &str) -> Result<(Slot, usize), SnapshotError> {
    let mut parts = filename.splitn(2, '.');
    let slot = parts.next().and_then(|s| Slot::from_str(s).ok());
    let id = parts.next().and_then(|s| usize::from_str(s).ok());

    slot.zip(id)
        .ok_or_else(|| SnapshotError::InvalidAppendVecPath(PathBuf::from(filename)))
}

#[cfg(test)]
mod tests {
    use {super::*, solana_accounts_db::accounts_file::AccountsFile};

    #[test]
    fn test_get_slot_and_append_vec_id() {
        let expected_slot = 12345;
        let expected_id = 9987;
        let (slot, id) =
            get_slot_and_append_vec_id(&AccountsFile::file_name(expected_slot, expected_id))
                .unwrap();
        assert_eq!(expected_slot, slot);
        assert_eq!(expected_id as usize, id);
    }
}
