pub(crate) const GUEST_REGION_SIZE: u64 = 1 << 32;
pub(crate) const GUEST_INSTRUCTION_ACCOUNTS_ADDRESS: u64 = 7 * GUEST_REGION_SIZE;
pub(crate) const GUEST_ACCOUNT_PAYLOAD_BASE_ADDRESS: u64 = 9 * GUEST_REGION_SIZE;
pub(crate) const GUEST_INSTRUCTION_DATA_BASE_ADDRESS: u64 = 265 * GUEST_REGION_SIZE;
