name: docs

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+

jobs:
  docs-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check
        id: check
        run: |
          source ci/env.sh
          echo "::set-output name=tag::$CI_TAG"
          ci/channel_restriction.sh edge beta
        continue-on-error: true

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v19
        with:
          files: |
            docs/**

      - name: Setup Node
        if: ${{ steps.check.outputs.tag || steps.changed-files-specific.outputs.any_changed }}
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build
        if: ${{ steps.check.outputs.tag || steps.changed-files-specific.outputs.any_changed }}
        working-directory: docs
        run: |
          npm install
          ./build.sh
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
