name: docs

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
    paths:
      - "docs/**"
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+

jobs:
  check:
    runs-on: ubuntu-20.04
    outputs:
      specific-file-changed: ${{ steps.changed-files-specific.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check
        run: |
          source ci/env.sh
          ci/channel_restriction.sh edge beta

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v19
        with:
          files: |
            docs/**
  build:
    needs:
      - check
    if: ${{ needs.check.outputs.specific-file-changed }} = 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build & Deploy (if needed)
        working-directory: docs
        run: |
          npm install
          ./build.sh
