name: release-artifacts-auto

on:
  push:
    tags:
      - "*"

jobs:
  release-artifacts:
    uses: ./.github/workflows/release-artifacts.yml
    with:
      tag: $GITHUB_REF_NAME
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
